version: '2'

services:

  php_fpm:
    build:
      context: .
      dockerfile: docker/phpFpm/dev/Dockerfile
    env_file: docker/.env
    links:
      - mysql:mysql
    ports:
      #php-fpm
      - "9093:9090"
    volumes:
      - .:/var/app


  nginx:
    build:
      context: .
      dockerfile: docker/nginx/dev/Dockerfile
    ports:
        - 8889:80
    expose:
      - 888
    links:
        - php_fpm
    volumes_from:
        - php_fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx


  mysql:
    image: mysql/mysql-server
    ports:
      - 3310:3306
    expose:
      - 3310
    environment:
      - MYSQL_DATABASE=vanilla
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./data:/docker-entrypoint-initdb.d