version: '2'
services:
  vanilla:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    links:
      - database:database
    ports:
      - "8888:80"
    expose:
      - "8888"
    volumes:
      - .:/var/app


  database:
    image: mysql
    ports:
      - "3308:3306"
    expose:
      - "3308"
    environment:
      - MYSQL_DATABASE=vanilla
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./data:/docker-entrypoint-initdb.d
