version: '2'
services:
  vanilla:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    links:
      - database:database
    ports:
      - "9999:80"
    expose:
      - "9999"
    volumes:
      - .:/var/app

    external_links:
      - necktie_web_1:necktie

  database:
    image: mysql
    ports:
      - "3310:3306"
    expose:
      - "3310"
    environment:
      - MYSQL_DATABASE=vanilla
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./data:/docker-entrypoint-initdb.d

networks:
  default:
    external:
      name: necktie_default
